\PassOptionsToPackage{unicode=true}{hyperref} % options for packages loaded elsewhere
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provides euro and other symbols
\else % if luatex or xelatex
  \usepackage{unicode-math}
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage[]{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\usepackage{hyperref}
\hypersetup{
            pdftitle={ca\_supp\_1},
            pdfauthor={od},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs}
% Fix footnotes in tables (requires footnote package)
\IfFileExists{footnote.sty}{\usepackage{footnote}\makesavenoteenv{longtable}}{}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

% set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother


\title{ca\_supp\_1}
\author{od}
\date{1/16/2020}

\begin{document}
\maketitle

\hypertarget{loading-required-pacakges-to-laod-datasets-manipulate-and-explore-some-outputs}{%
\subsection{Loading required pacakges to laod datasets, manipulate and
explore some
outputs}\label{loading-required-pacakges-to-laod-datasets-manipulate-and-explore-some-outputs}}

\hypertarget{reading-datasets-in-r-with-h5ls}{%
\subsection{Reading datasets in R with
h5ls}\label{reading-datasets-in-r-with-h5ls}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{h5ls}\NormalTok{(}\StringTok{"DataSets/output.hdf"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   group          name       otype  dclass         dim
## 0     /          data   H5I_GROUP                    
## 1 /data         axis0 H5I_DATASET  STRING        1382
## 2 /data  axis1_label0 H5I_DATASET INTEGER        3998
## 3 /data  axis1_label1 H5I_DATASET INTEGER        3998
## 4 /data  axis1_level0 H5I_DATASET   FLOAT         200
## 5 /data  axis1_level1 H5I_DATASET   FLOAT          10
## 6 /data  block0_items H5I_DATASET  STRING        1382
## 7 /data block0_values H5I_DATASET   FLOAT 1382 x 3998
\end{verbatim}

\hypertarget{eda-1}{%
\subsection{EDA 1:}\label{eda-1}}

\begin{itemize}
\tightlist
\item
  The first file (renamed here `axis\_0') and the `items' file are
  similar with dimensions = 1382
\item
  Files label0, label1, level0 and level1 have 3998, 3998, 200 and 10
  elements respectivily.
\item
  files renamed here `values' is the only one in array shape with
  dimensions (1382, 3998)
\end{itemize}

Question: how are the 4 files {[}label0, label1, level0 and level1{]}
related to the other files?

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{h5read}\NormalTok{(}\StringTok{"DataSets/output.hdf"}\NormalTok{, }\DataTypeTok{name =} \StringTok{"data/axis0"}\NormalTok{)  ->}\StringTok{ }\NormalTok{axis_}\DecValTok{0}
\KeywordTok{h5read}\NormalTok{(}\StringTok{"DataSets/output.hdf"}\NormalTok{, }\DataTypeTok{name =} \StringTok{"data/axis1_label0"}\NormalTok{)  ->}\StringTok{ }\NormalTok{label0}
\KeywordTok{h5read}\NormalTok{(}\StringTok{"DataSets/output.hdf"}\NormalTok{, }\DataTypeTok{name =} \StringTok{"data/axis1_label1"}\NormalTok{)  ->}\StringTok{ }\NormalTok{label1}
\KeywordTok{h5read}\NormalTok{(}\StringTok{"DataSets/output.hdf"}\NormalTok{, }\DataTypeTok{name =} \StringTok{"data/axis1_level0"}\NormalTok{)  ->}\StringTok{ }\NormalTok{level0}
\KeywordTok{h5read}\NormalTok{(}\StringTok{"DataSets/output.hdf"}\NormalTok{, }\DataTypeTok{name =} \StringTok{"data/axis1_level1"}\NormalTok{)  ->}\StringTok{ }\NormalTok{level1}
\KeywordTok{h5read}\NormalTok{(}\StringTok{"DataSets/output.hdf"}\NormalTok{, }\DataTypeTok{name =} \StringTok{"data/block0_items"}\NormalTok{)  ->}\StringTok{ }\NormalTok{items}
\KeywordTok{h5read}\NormalTok{(}\StringTok{"DataSets/output.hdf"}\NormalTok{, }\DataTypeTok{name =} \StringTok{"data/block0_values"}\NormalTok{) ->}\StringTok{ }\NormalTok{values}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{axis_}\DecValTok{0} \OperatorTok{%>%}\StringTok{ }\KeywordTok{dim}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1382
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{label0 }\OperatorTok{%>%}\StringTok{ }\KeywordTok{dim}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3998
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{label1 }\OperatorTok{%>%}\StringTok{ }\KeywordTok{dim}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3998
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{level0 }\OperatorTok{%>%}\StringTok{ }\KeywordTok{dim}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 200
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{level1 }\OperatorTok{%>%}\StringTok{ }\KeywordTok{dim}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 10
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{items }\OperatorTok{%>%}\StringTok{ }\KeywordTok{dim}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1382
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{values }\OperatorTok{%>%}\StringTok{ }\KeywordTok{dim}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1382 3998
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{axis_}\DecValTok{0} \OperatorTok{%>%}\StringTok{ }\NormalTok{head}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "total_population_untracked"                                                  
## [2] "total_population_tracked"                                                    
## [3] "total_population"                                                            
## [4] "death_due_to_neonatal_preterm_birth_among_male_in_age_group_early_neonatal"  
## [5] "death_due_to_neonatal_preterm_birth_among_female_in_age_group_early_neonatal"
## [6] "death_due_to_neonatal_preterm_birth_among_male_in_age_group_late_neonatal"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{label0 }\OperatorTok{%>%}\StringTok{ }\NormalTok{head}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 188 122  26  90  82  41
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{label1 }\OperatorTok{%>%}\StringTok{ }\NormalTok{head}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 9 9 1 5 1 7
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{level0 }\OperatorTok{%>%}\StringTok{ }\NormalTok{head}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  1  3  8 14 21 29
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{level1 }\OperatorTok{%>%}\StringTok{ }\NormalTok{head}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  0  2 30 38 43 58
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{items }\OperatorTok{%>%}\StringTok{ }\NormalTok{head}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "total_population_untracked"                                                  
## [2] "total_population_tracked"                                                    
## [3] "total_population"                                                            
## [4] "death_due_to_neonatal_preterm_birth_among_male_in_age_group_early_neonatal"  
## [5] "death_due_to_neonatal_preterm_birth_among_female_in_age_group_early_neonatal"
## [6] "death_due_to_neonatal_preterm_birth_among_male_in_age_group_late_neonatal"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{values[}\DecValTok{1}\OperatorTok{:}\DecValTok{10}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1]  9623 12221 21844   120    74     4     7     2     2     0
\end{verbatim}

\hypertarget{data-wrangling-process}{%
\subsection{Data wrangling process:}\label{data-wrangling-process}}

\begin{itemize}
\tightlist
\item
  After viewing the file in PYTHON, I realised that `items' file
  contains the rows names from the orginal dataset.
\item
  That is what I tried to replicate in the following section using only
  values file and items file.

  \begin{itemize}
  \tightlist
  \item
    first step: transpose the array (rows-to-columns)
  \item
    second step: add `items' containt as columns names
  \end{itemize}
\item
  output: draft\_1
\end{itemize}

\hypertarget{section}{%
\subsubsection{}\label{section}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{t_values <-}\StringTok{ }\KeywordTok{t}\NormalTok{(values)}
\KeywordTok{colnames}\NormalTok{(t_values) <-}\StringTok{ }\NormalTok{items}
\NormalTok{t_values[}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{3}\NormalTok{), }\KeywordTok{c}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{3}\NormalTok{)]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      total_population_untracked total_population_tracked total_population
## [1,]                       9623                    12221            21844
## [2,]                       9561                    12061            21622
## [3,]                       9626                    12081            21707
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{t_values[}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{3}\NormalTok{), }\KeywordTok{c}\NormalTok{(}\DecValTok{1380}\OperatorTok{:}\DecValTok{1382}\NormalTok{)]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      low_birth_weight_and_short_gestation_cat212_exposed_in_2024_among_1_to_4
## [1,]                                                                      NaN
## [2,]                                                                        2
## [3,]                                                                      NaN
##      simulation_run_time calcium_supplementation_intervention.proportion
## [1,]            9960.960                                               0
## [2,]            9948.302                                               1
## [3,]           10118.156                                               1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{draft_}\DecValTok{1}\NormalTok{ <-}\StringTok{ }\KeywordTok{as_tibble}\NormalTok{(t_values)}
\NormalTok{draft_}\DecValTok{1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 3,998 x 1,382
##    total_populatio~ total_populatio~ total_population death_due_to_ne~
##               <dbl>            <dbl>            <dbl>            <dbl>
##  1             9623            12221            21844              120
##  2             9561            12061            21622               95
##  3             9626            12081            21707               90
##  4             9599            11822            21421               94
##  5             9529            12333            21862              181
##  6             9608            12357            21965              187
##  7             9626            12096            21722              150
##  8             9639            12053            21692              126
##  9             9553            12225            21778              156
## 10             9618            12225            21843               97
## # ... with 3,988 more rows, and 1,378 more variables:
## #   death_due_to_neonatal_preterm_birth_among_female_in_age_group_early_neonatal <dbl>,
## #   death_due_to_neonatal_preterm_birth_among_male_in_age_group_late_neonatal <dbl>,
## #   death_due_to_neonatal_preterm_birth_among_female_in_age_group_late_neonatal <dbl>,
## #   death_due_to_neonatal_preterm_birth_among_male_in_age_group_post_neonatal <dbl>,
## #   death_due_to_neonatal_preterm_birth_among_female_in_age_group_post_neonatal <dbl>,
## #   death_due_to_neonatal_preterm_birth_among_male_in_age_group_1_to_4 <dbl>,
## #   death_due_to_neonatal_preterm_birth_among_female_in_age_group_1_to_4 <dbl>,
## #   death_due_to_diarrheal_diseases_among_male_in_age_group_early_neonatal <dbl>,
## #   death_due_to_diarrheal_diseases_among_female_in_age_group_early_neonatal <dbl>,
## #   death_due_to_diarrheal_diseases_among_male_in_age_group_late_neonatal <dbl>,
## #   death_due_to_diarrheal_diseases_among_female_in_age_group_late_neonatal <dbl>,
## #   death_due_to_diarrheal_diseases_among_male_in_age_group_post_neonatal <dbl>,
## #   death_due_to_diarrheal_diseases_among_female_in_age_group_post_neonatal <dbl>,
## #   death_due_to_diarrheal_diseases_among_male_in_age_group_1_to_4 <dbl>,
## #   death_due_to_diarrheal_diseases_among_female_in_age_group_1_to_4 <dbl>,
## #   death_due_to_lower_respiratory_infections_among_male_in_age_group_early_neonatal <dbl>,
## #   death_due_to_lower_respiratory_infections_among_female_in_age_group_early_neonatal <dbl>,
## #   death_due_to_lower_respiratory_infections_among_male_in_age_group_late_neonatal <dbl>,
## #   death_due_to_lower_respiratory_infections_among_female_in_age_group_late_neonatal <dbl>,
## #   death_due_to_lower_respiratory_infections_among_male_in_age_group_post_neonatal <dbl>,
## #   death_due_to_lower_respiratory_infections_among_female_in_age_group_post_neonatal <dbl>,
## #   death_due_to_lower_respiratory_infections_among_male_in_age_group_1_to_4 <dbl>,
## #   death_due_to_lower_respiratory_infections_among_female_in_age_group_1_to_4 <dbl>,
## #   death_due_to_measles_among_male_in_age_group_early_neonatal <dbl>,
## #   death_due_to_measles_among_female_in_age_group_early_neonatal <dbl>,
## #   death_due_to_measles_among_male_in_age_group_late_neonatal <dbl>,
## #   death_due_to_measles_among_female_in_age_group_late_neonatal <dbl>,
## #   death_due_to_measles_among_male_in_age_group_post_neonatal <dbl>,
## #   death_due_to_measles_among_female_in_age_group_post_neonatal <dbl>,
## #   death_due_to_measles_among_male_in_age_group_1_to_4 <dbl>,
## #   death_due_to_measles_among_female_in_age_group_1_to_4 <dbl>,
## #   death_due_to_neonatal_sepsis_and_other_neonatal_infections_among_male_in_age_group_early_neonatal <dbl>,
## #   death_due_to_neonatal_sepsis_and_other_neonatal_infections_among_female_in_age_group_early_neonatal <dbl>,
## #   death_due_to_neonatal_sepsis_and_other_neonatal_infections_among_male_in_age_group_late_neonatal <dbl>,
## #   death_due_to_neonatal_sepsis_and_other_neonatal_infections_among_female_in_age_group_late_neonatal <dbl>,
## #   death_due_to_neonatal_sepsis_and_other_neonatal_infections_among_male_in_age_group_post_neonatal <dbl>,
## #   death_due_to_neonatal_sepsis_and_other_neonatal_infections_among_female_in_age_group_post_neonatal <dbl>,
## #   death_due_to_neonatal_sepsis_and_other_neonatal_infections_among_male_in_age_group_1_to_4 <dbl>,
## #   death_due_to_neonatal_sepsis_and_other_neonatal_infections_among_female_in_age_group_1_to_4 <dbl>,
## #   death_due_to_neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma_among_male_in_age_group_early_neonatal <dbl>,
## #   death_due_to_neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma_among_female_in_age_group_early_neonatal <dbl>,
## #   death_due_to_neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma_among_male_in_age_group_late_neonatal <dbl>,
## #   death_due_to_neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma_among_female_in_age_group_late_neonatal <dbl>,
## #   death_due_to_neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma_among_male_in_age_group_post_neonatal <dbl>,
## #   death_due_to_neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma_among_female_in_age_group_post_neonatal <dbl>,
## #   death_due_to_neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma_among_male_in_age_group_1_to_4 <dbl>,
## #   death_due_to_neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma_among_female_in_age_group_1_to_4 <dbl>,
## #   death_due_to_hemolytic_disease_and_other_neonatal_jaundice_among_male_in_age_group_early_neonatal <dbl>,
## #   death_due_to_hemolytic_disease_and_other_neonatal_jaundice_among_female_in_age_group_early_neonatal <dbl>,
## #   death_due_to_hemolytic_disease_and_other_neonatal_jaundice_among_male_in_age_group_late_neonatal <dbl>,
## #   death_due_to_hemolytic_disease_and_other_neonatal_jaundice_among_female_in_age_group_late_neonatal <dbl>,
## #   death_due_to_hemolytic_disease_and_other_neonatal_jaundice_among_male_in_age_group_post_neonatal <dbl>,
## #   death_due_to_hemolytic_disease_and_other_neonatal_jaundice_among_female_in_age_group_post_neonatal <dbl>,
## #   death_due_to_hemolytic_disease_and_other_neonatal_jaundice_among_male_in_age_group_1_to_4 <dbl>,
## #   death_due_to_hemolytic_disease_and_other_neonatal_jaundice_among_female_in_age_group_1_to_4 <dbl>,
## #   death_due_to_other_causes_among_male_in_age_group_early_neonatal <dbl>,
## #   death_due_to_other_causes_among_female_in_age_group_early_neonatal <dbl>,
## #   death_due_to_other_causes_among_male_in_age_group_late_neonatal <dbl>,
## #   death_due_to_other_causes_among_female_in_age_group_late_neonatal <dbl>,
## #   death_due_to_other_causes_among_male_in_age_group_post_neonatal <dbl>,
## #   death_due_to_other_causes_among_female_in_age_group_post_neonatal <dbl>,
## #   death_due_to_other_causes_among_male_in_age_group_1_to_4 <dbl>,
## #   death_due_to_other_causes_among_female_in_age_group_1_to_4 <dbl>,
## #   ylls_due_to_neonatal_preterm_birth_among_male_in_age_group_1_to_4 <dbl>,
## #   ylls_due_to_neonatal_preterm_birth_among_female_in_age_group_1_to_4 <dbl>,
## #   ylls_due_to_lower_respiratory_infections_among_male_in_age_group_early_neonatal <dbl>,
## #   ylls_due_to_lower_respiratory_infections_among_female_in_age_group_early_neonatal <dbl>,
## #   ylls_due_to_lower_respiratory_infections_among_male_in_age_group_late_neonatal <dbl>,
## #   ylls_due_to_measles_among_male_in_age_group_early_neonatal <dbl>,
## #   ylls_due_to_measles_among_female_in_age_group_early_neonatal <dbl>,
## #   ylls_due_to_measles_among_male_in_age_group_late_neonatal <dbl>,
## #   ylls_due_to_measles_among_female_in_age_group_late_neonatal <dbl>,
## #   ylls_due_to_neonatal_sepsis_and_other_neonatal_infections_among_male_in_age_group_1_to_4 <dbl>,
## #   ylls_due_to_neonatal_sepsis_and_other_neonatal_infections_among_female_in_age_group_1_to_4 <dbl>,
## #   ylls_due_to_neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma_among_male_in_age_group_1_to_4 <dbl>,
## #   ylls_due_to_neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma_among_female_in_age_group_1_to_4 <dbl>,
## #   ylls_due_to_hemolytic_disease_and_other_neonatal_jaundice_among_male_in_age_group_late_neonatal <dbl>,
## #   ylls_due_to_hemolytic_disease_and_other_neonatal_jaundice_among_female_in_age_group_late_neonatal <dbl>,
## #   ylls_due_to_hemolytic_disease_and_other_neonatal_jaundice_among_male_in_age_group_1_to_4 <dbl>,
## #   ylls_due_to_hemolytic_disease_and_other_neonatal_jaundice_among_female_in_age_group_1_to_4 <dbl>,
## #   total_population_living <dbl>, total_population_dead <dbl>,
## #   diarrheal_diseases_prevalent_cases_at_sim_end <dbl>,
## #   lower_respiratory_infections_prevalent_cases_at_sim_end <dbl>,
## #   measles_prevalent_cases_at_sim_end <dbl>,
## #   neonatal_sepsis_and_other_neonatal_infections_prevalent_cases_at_sim_end <dbl>,
## #   neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma_prevalent_cases_at_sim_end <dbl>,
## #   hemolytic_disease_and_other_neonatal_jaundice_prevalent_cases_at_sim_end <dbl>,
## #   susceptible_to_diarrheal_diseases_event_count <dbl>,
## #   diarrheal_diseases_event_count <dbl>,
## #   susceptible_to_lower_respiratory_infections_event_count <dbl>,
## #   lower_respiratory_infections_event_count <dbl>,
## #   susceptible_to_measles_event_count <dbl>, measles_event_count <dbl>,
## #   recovered_from_measles_event_count <dbl>,
## #   susceptible_to_neonatal_sepsis_and_other_neonatal_infections_event_count <dbl>,
## #   neonatal_sepsis_and_other_neonatal_infections_event_count <dbl>,
## #   susceptible_to_neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma_event_count <dbl>,
## #   neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma_event_count <dbl>,
## #   susceptible_to_hemolytic_disease_and_other_neonatal_jaundice_event_count <dbl>,
## #   ...
\end{verbatim}

\hypertarget{saving-the-final-dataset}{%
\subsection{Saving the final dataset:}\label{saving-the-final-dataset}}

\begin{itemize}
\tightlist
\item
  Getting the output\_1 file took few steps:
\item
  step-1: grouping 9 columns (listed here) and gathering all the rest in
  one column `item'. total\_population\_untracked\\
  total\_population\_tracked\\
  total\_population\\
  total\_population\_living\\
  total\_population\_dead\\
  input\_draw\\
  random\_seed\\
  simulation\_run\_time\\
  calcium\_supplementation\_intervention.proportion
\item
  step-2:

  \begin{itemize}
  \tightlist
  \item
    seperating gender, age\_group ('item\_age\_group) where relevent
  \item
    separating item and outcome/risk into: {[}item, item\_outcome{]}
  \item
    separate cat\#\# and exposure year form
    low\_birth\_weight\_and\_short\_gestation question: is it that
    useful for analysis?
  \end{itemize}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{output_}\DecValTok{1}\NormalTok{ <-}\StringTok{ }\NormalTok{draft_}\DecValTok{1} \OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{select}\NormalTok{(}\KeywordTok{contains}\NormalTok{(}\StringTok{"years_"}\NormalTok{), }\KeywordTok{everything}\NormalTok{()) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{select}\NormalTok{(}\KeywordTok{contains}\NormalTok{(}\StringTok{"_event_"}\NormalTok{), }\KeywordTok{everything}\NormalTok{()) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{select}\NormalTok{(}\KeywordTok{contains}\NormalTok{(}\StringTok{"_cases_at_sim_"}\NormalTok{), }\KeywordTok{everything}\NormalTok{()) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{select}\NormalTok{(}\KeywordTok{contains}\NormalTok{(}\StringTok{"_exposed_"}\NormalTok{), }\KeywordTok{everything}\NormalTok{()) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{select}\NormalTok{(}\KeywordTok{contains}\NormalTok{(}\StringTok{"person_time"}\NormalTok{), }\KeywordTok{everything}\NormalTok{()) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{select}\NormalTok{(}\KeywordTok{contains}\NormalTok{(}\StringTok{"ylls_due"}\NormalTok{), }\KeywordTok{everything}\NormalTok{()) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{select}\NormalTok{(}\KeywordTok{contains}\NormalTok{(}\StringTok{"ylds_due"}\NormalTok{), }\KeywordTok{everything}\NormalTok{()) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{select}\NormalTok{(}\KeywordTok{contains}\NormalTok{(}\StringTok{"death_due"}\NormalTok{), }\KeywordTok{everything}\NormalTok{()) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{gather}\NormalTok{(}\StringTok{"item"}\NormalTok{, }\StringTok{"value"}\NormalTok{, }\DecValTok{1}\OperatorTok{:}\DecValTok{1373}\NormalTok{) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{select}\NormalTok{(}\DecValTok{10}\NormalTok{, }\KeywordTok{everything}\NormalTok{()) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{item =} \KeywordTok{str_replace_all}\NormalTok{(item, }\StringTok{'20_among_'}\NormalTok{, }\StringTok{'20_sep_'}\NormalTok{)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{item =} \KeywordTok{str_replace_all}\NormalTok{(item, }\StringTok{'21_among_'}\NormalTok{, }\StringTok{'21_sep_'}\NormalTok{)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{item =} \KeywordTok{str_replace_all}\NormalTok{(item, }\StringTok{'22_among_'}\NormalTok{, }\StringTok{'22_sep_'}\NormalTok{)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{item =} \KeywordTok{str_replace_all}\NormalTok{(item, }\StringTok{'23_among_'}\NormalTok{, }\StringTok{'23_sep_'}\NormalTok{)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{item =} \KeywordTok{str_replace_all}\NormalTok{(item, }\StringTok{'24_among_'}\NormalTok{, }\StringTok{'24_sep_'}\NormalTok{)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{item =} \KeywordTok{str_replace_all}\NormalTok{(item, }\StringTok{'_in_age_group_'}\NormalTok{, }\StringTok{'_sep_'}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{separate}\NormalTok{(item, }
           \KeywordTok{c}\NormalTok{(}\StringTok{'item'}\NormalTok{, }\StringTok{'item_age_group'}\NormalTok{), }
           \DataTypeTok{sep =} \StringTok{'_sep_'}\NormalTok{) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{item =} \KeywordTok{str_replace_all}\NormalTok{(item, }\StringTok{'_exposed_in_20'}\NormalTok{, }\StringTok{'_sep2_20'}\NormalTok{))}\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{separate}\NormalTok{(item, }
           \KeywordTok{c}\NormalTok{(}\StringTok{'item'}\NormalTok{, }\StringTok{'exposed_in'}\NormalTok{), }
           \DataTypeTok{sep =} \StringTok{'_sep2_'}\NormalTok{) }\OperatorTok{%>%}\StringTok{  }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{item =} \KeywordTok{str_replace_all}\NormalTok{(item, }\StringTok{'gestation_cat'}\NormalTok{, }\StringTok{'gestation_sep3_cat'}\NormalTok{))   }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{separate}\NormalTok{(item, }
           \KeywordTok{c}\NormalTok{(}\StringTok{'item'}\NormalTok{, }\StringTok{'lbw_sg_cat'}\NormalTok{), }
           \DataTypeTok{sep =} \StringTok{'_sep3_'}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{item =} \KeywordTok{str_replace_all}\NormalTok{(item, }\StringTok{'_among_male'}\NormalTok{, }\StringTok{'_sep4_male'}\NormalTok{)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{item =} \KeywordTok{str_replace_all}\NormalTok{(item, }\StringTok{'_among_female'}\NormalTok{, }\StringTok{'_sep4_female'}\NormalTok{)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{separate}\NormalTok{(item, }
           \KeywordTok{c}\NormalTok{(}\StringTok{'item'}\NormalTok{, }\StringTok{'gender'}\NormalTok{), }
           \DataTypeTok{sep =} \StringTok{'_sep4_'}\NormalTok{) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{item =} \KeywordTok{str_replace_all}\NormalTok{(item, }\StringTok{'th_due_to_'}\NormalTok{, }\StringTok{'th_sep5_'}\NormalTok{)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{item =} \KeywordTok{str_replace_all}\NormalTok{(item, }\StringTok{'ds_due_to_'}\NormalTok{, }\StringTok{'ds_sep5_'}\NormalTok{)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{item =} \KeywordTok{str_replace_all}\NormalTok{(item, }\StringTok{'ls_due_to_'}\NormalTok{, }\StringTok{'ls_sep5_'}\NormalTok{)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{separate}\NormalTok{(item, }
           \KeywordTok{c}\NormalTok{(}\StringTok{'item'}\NormalTok{, }\StringTok{'item_outcome'}\NormalTok{), }
           \DataTypeTok{sep =} \StringTok{'_sep5_'}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

Not all elements in `item' column can be separateed in gender / age
group. For somes elements, there no gender or age group, which explains
all the NA in those new columns.

What I was not expecting is to have NAs in the `value' column. They are
all in one item type (See the tbl\_df ot next section)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{output_}\DecValTok{1} \OperatorTok{%>%}\StringTok{ }\NormalTok{head}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 16
##   item  item_outcome gender lbw_sg_cat exposed_in item_age_group
##   <chr> <chr>        <chr>  <chr>      <chr>      <chr>         
## 1 death neonatal_pr~ male   <NA>       <NA>       early_neonatal
## 2 death neonatal_pr~ male   <NA>       <NA>       early_neonatal
## 3 death neonatal_pr~ male   <NA>       <NA>       early_neonatal
## 4 death neonatal_pr~ male   <NA>       <NA>       early_neonatal
## 5 death neonatal_pr~ male   <NA>       <NA>       early_neonatal
## 6 death neonatal_pr~ male   <NA>       <NA>       early_neonatal
## # ... with 10 more variables: total_population_untracked <dbl>,
## #   total_population_tracked <dbl>, total_population <dbl>,
## #   total_population_living <dbl>, total_population_dead <dbl>,
## #   input_draw <dbl>, random_seed <dbl>, simulation_run_time <dbl>,
## #   calcium_supplementation_intervention.proportion <dbl>, value <dbl>
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{output_}\DecValTok{1} \OperatorTok{%>%}\StringTok{ }\KeywordTok{select}\NormalTok{(value) }\OperatorTok{%>%}\StringTok{ }\NormalTok{skim}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}ll@{}}
\caption{Data summary}\tabularnewline
\toprule
\endhead
Name & Piped data\tabularnewline
Number of rows & 5489254\tabularnewline
Number of columns & 1\tabularnewline
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ &\tabularnewline
Column type frequency: &\tabularnewline
numeric & 1\tabularnewline
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ &\tabularnewline
Group variables & None\tabularnewline
\bottomrule
\end{longtable}

\textbf{Variable type: numeric}

\begin{longtable}[]{@{}lrrrrrrrrrl@{}}
\toprule
skim\_variable & n\_missing & complete\_rate & mean & sd & p0 & p25 &
p50 & p75 & p100 & hist\tabularnewline
\midrule
\endhead
value & 1806953 & 0.67 & 541.62 & 5431.29 & 0 & 2 & 7 & 28 & 165541.1 &
▇▁▁▁▁\tabularnewline
\bottomrule
\end{longtable}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{output_}\DecValTok{1} \OperatorTok{%>%}\StringTok{ }\KeywordTok{filter}\NormalTok{(}\KeywordTok{is.na}\NormalTok{(value)) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1,806,953 x 16
##    item  item_outcome gender lbw_sg_cat exposed_in item_age_group
##    <chr> <chr>        <chr>  <chr>      <chr>      <chr>         
##  1 low_~ <NA>         <NA>   cat2       2020       early_neonatal
##  2 low_~ <NA>         <NA>   cat2       2020       early_neonatal
##  3 low_~ <NA>         <NA>   cat2       2020       early_neonatal
##  4 low_~ <NA>         <NA>   cat2       2020       early_neonatal
##  5 low_~ <NA>         <NA>   cat2       2020       early_neonatal
##  6 low_~ <NA>         <NA>   cat2       2020       early_neonatal
##  7 low_~ <NA>         <NA>   cat2       2020       early_neonatal
##  8 low_~ <NA>         <NA>   cat2       2020       early_neonatal
##  9 low_~ <NA>         <NA>   cat2       2020       early_neonatal
## 10 low_~ <NA>         <NA>   cat2       2020       early_neonatal
## # ... with 1,806,943 more rows, and 10 more variables:
## #   total_population_untracked <dbl>, total_population_tracked <dbl>,
## #   total_population <dbl>, total_population_living <dbl>,
## #   total_population_dead <dbl>, input_draw <dbl>, random_seed <dbl>,
## #   simulation_run_time <dbl>,
## #   calcium_supplementation_intervention.proportion <dbl>, value <dbl>
\end{verbatim}

NAs: Almost half of `low\_birth\_weight\_and\_short\_gestation' in item
column have corresponding NAs in value column.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{output_}\DecValTok{1}\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(item) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{pct =} \KeywordTok{mean}\NormalTok{(}\KeywordTok{is.na}\NormalTok{(value)) }\OperatorTok{*}\StringTok{ }\DecValTok{100}\NormalTok{) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(pct)) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 26 x 2
##    item                                                                      pct
##    <chr>                                                                   <dbl>
##  1 low_birth_weight_and_short_gestation                                     39.0
##  2 death                                                                     0  
##  3 diarrheal_diseases_event_count                                            0  
##  4 diarrheal_diseases_prevalent_cases_at_sim_end                             0  
##  5 hemolytic_disease_and_other_neonatal_jaundice_event_count                 0  
##  6 hemolytic_disease_and_other_neonatal_jaundice_prevalent_cases_at_sim_e~   0  
##  7 lower_respiratory_infections_event_count                                  0  
##  8 lower_respiratory_infections_prevalent_cases_at_sim_end                   0  
##  9 measles_event_count                                                       0  
## 10 measles_prevalent_cases_at_sim_end                                        0  
## # ... with 16 more rows
\end{verbatim}

\hypertarget{saving-output_1-files}{%
\subsection{Saving output\_1 files:}\label{saving-output_1-files}}

\begin{itemize}
\tightlist
\item
  you can save the file by replacing `Output\_Files/' with the current
  directory.
\item
  can ignore this part {[}saving output\_1.csv{]} for space/time sake
  and just run the rest of the code
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{write_csv}\NormalTok{(output_}\DecValTok{1}\NormalTok{, }\StringTok{'Output_Files/output_1.csv'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{draft_}\DecValTok{2}\NormalTok{ <-}\StringTok{ }\KeywordTok{read_csv}\NormalTok{(}\StringTok{'Output_Files/output_1.csv'}\NormalTok{,}
               \DataTypeTok{col_types =} \KeywordTok{list}\NormalTok{(}
                 \DataTypeTok{item =} \KeywordTok{col_character}\NormalTok{(),}
                 \DataTypeTok{item_outcome =} \KeywordTok{col_character}\NormalTok{(),}
                 \DataTypeTok{gender =} \KeywordTok{col_character}\NormalTok{(),}
                 \DataTypeTok{lbw_sg_cat =} \KeywordTok{col_character}\NormalTok{(),}
                 \DataTypeTok{exposed_in =} \KeywordTok{col_character}\NormalTok{(),}
                 \DataTypeTok{item_age_group =} \KeywordTok{col_character}\NormalTok{(),}
                 \DataTypeTok{total_population_untracked =} \KeywordTok{col_double}\NormalTok{(),}
                 \DataTypeTok{total_population_tracked =} \KeywordTok{col_double}\NormalTok{(),}
                 \DataTypeTok{total_population =} \KeywordTok{col_double}\NormalTok{(),}
                 \DataTypeTok{total_population_living =} \KeywordTok{col_double}\NormalTok{(),}
                 \DataTypeTok{total_population_dead =} \KeywordTok{col_double}\NormalTok{(),}
                 \DataTypeTok{input_draw =} \KeywordTok{col_double}\NormalTok{(),}
                 \DataTypeTok{random_seed =} \KeywordTok{col_double}\NormalTok{(),}
                 \DataTypeTok{simulation_run_time =} \KeywordTok{col_double}\NormalTok{(),}
                 \DataTypeTok{calcium_supplementation_intervention.proportion =} \KeywordTok{col_character}\NormalTok{(),}
                 \DataTypeTok{value =} \KeywordTok{col_double}\NormalTok{()))}
\end{Highlighting}
\end{Shaded}

Converting to factor: gender, age group, calcium supplementation and
reproducing the ealier graph

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{draft_}\DecValTok{2} \OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{distinct}\NormalTok{(item_age_group)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 5 x 1
##   item_age_group
##   <chr>         
## 1 early_neonatal
## 2 late_neonatal 
## 3 post_neonatal 
## 4 1_to_4        
## 5 <NA>
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lbls <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"1_to_4"}\NormalTok{, }\StringTok{"Early neonatal"}\NormalTok{, }\StringTok{"Late neonatal"}\NormalTok{ , }\StringTok{"Post neonatal"}\NormalTok{)}

\NormalTok{final_dataset <-}\StringTok{ }\NormalTok{draft_}\DecValTok{2} \OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{gender =} \KeywordTok{factor}\NormalTok{(gender, }
                         \DataTypeTok{labels =} \KeywordTok{c}\NormalTok{(}\StringTok{'Female'}\NormalTok{, }\StringTok{'Male'}\NormalTok{))) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{age_group =} \KeywordTok{factor}\NormalTok{(item_age_group,}
                                 \DataTypeTok{labels =}\NormalTok{ lbls)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{ca_supp =} \KeywordTok{factor}\NormalTok{(calcium_supplementation_intervention.proportion,}
                          \DataTypeTok{labels =} \KeywordTok{c}\NormalTok{(}\StringTok{'NO'}\NormalTok{, }\StringTok{'YES'}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\hypertarget{saving-final_dataset}{%
\subsection{Saving final\_dataset:}\label{saving-final_dataset}}

\begin{itemize}
\tightlist
\item
  you can save the file by replacing `Output\_Files/' with the current
  directory.
\item
  can ignore this part {[}saving final\_dataset.csv{]} for space/time
  sake and just run the rest of the code
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{write_csv}\NormalTok{(final_dataset, }\StringTok{'Output_Files/final_dataset.csv'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{example-of-plot}{%
\subsection{Example of plot}\label{example-of-plot}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{final_dataset }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(item }\OperatorTok{==}\StringTok{'death'}\NormalTok{) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(item_outcome }\OperatorTok{==}\StringTok{ 'neonatal_preterm_birth'}\NormalTok{) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(item_age_group }\OperatorTok{%in%}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{'early_neonatal'}\NormalTok{,}
                               \StringTok{'late_neonatal'}\NormalTok{)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(value,}
             \DataTypeTok{color =}\NormalTok{ ca_supp,}
             \DataTypeTok{fill =}\NormalTok{ ca_supp))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_density}\NormalTok{(}\DataTypeTok{size =} \DecValTok{1}\NormalTok{, }\DataTypeTok{alpha =} \FloatTok{.3}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{facet_grid}\NormalTok{(gender }\OperatorTok{~}\StringTok{ }\NormalTok{age_group, }\DataTypeTok{scales =} \StringTok{'free'}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title =} \StringTok{'Death due to neonatal preterm birth'}\NormalTok{,}
       \DataTypeTok{subtitle =} \StringTok{'By age-group and by gender}\CharTok{\textbackslash{}n\textbackslash{}n}\StringTok{'}\NormalTok{,}
       \DataTypeTok{color =} \StringTok{'Calcium }\CharTok{\textbackslash{}n}\StringTok{Supplementation'}\NormalTok{,}
       \DataTypeTok{x =} \StringTok{''}\NormalTok{, }\DataTypeTok{y =} \StringTok{''}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{guides}\NormalTok{(}\DataTypeTok{fill =} \OtherTok{FALSE}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_bw}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_color_manual}\NormalTok{(}\DataTypeTok{values =} \KeywordTok{c}\NormalTok{(}\StringTok{'firebrick'}\NormalTok{, }\StringTok{'darkgreen'}\NormalTok{))}\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position =} \KeywordTok{c}\NormalTok{(.}\DecValTok{9}\NormalTok{,}\FloatTok{1.065}\NormalTok{),}
        \DataTypeTok{legend.direction =} \StringTok{'horizontal'}\NormalTok{,}
        \DataTypeTok{strip.text =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{size =} \DecValTok{10}\NormalTok{),}
        \DataTypeTok{axis.text.y =} \KeywordTok{element_blank}\NormalTok{(),}
        \DataTypeTok{plot.title =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{face =} \StringTok{'bold'}\NormalTok{, }\DataTypeTok{size =} \DecValTok{15}\NormalTok{),}
        \DataTypeTok{panel.background =} \KeywordTok{element_rect}\NormalTok{(}\DataTypeTok{colour =} \StringTok{'black'}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{ca_script_1_files/figure-latex/unnamed-chunk-14-1} \end{center}

\hypertarget{rerun-draft_2-to-get-final-dataset-for-the-following-steps}{%
\paragraph{rerun draft\_2 to get final dataset for the following
steps}\label{rerun-draft_2-to-get-final-dataset-for-the-following-steps}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{final_dataset }\OperatorTok{%>%}\StringTok{ }\KeywordTok{glimpse}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Observations: 5,489,254
## Variables: 18
## $ item                                            <chr> "death", "death", "...
## $ item_outcome                                    <chr> "neonatal_preterm_b...
## $ gender                                          <fct> Male, Male, Male, M...
## $ lbw_sg_cat                                      <chr> NA, NA, NA, NA, NA,...
## $ exposed_in                                      <chr> NA, NA, NA, NA, NA,...
## $ item_age_group                                  <chr> "early_neonatal", "...
## $ total_population_untracked                      <dbl> 9623, 9561, 9626, 9...
## $ total_population_tracked                        <dbl> 12221, 12061, 12081...
## $ total_population                                <dbl> 21844, 21622, 21707...
## $ total_population_living                         <dbl> 10853, 10522, 10728...
## $ total_population_dead                           <dbl> 1368, 1539, 1353, 1...
## $ input_draw                                      <dbl> 928, 590, 146, 465,...
## $ random_seed                                     <dbl> 97, 97, 2, 58, 2, 8...
## $ simulation_run_time                             <dbl> 9960.960, 9948.302,...
## $ calcium_supplementation_intervention.proportion <chr> "0", "1", "1", "1",...
## $ value                                           <dbl> 120, 95, 90, 94, 18...
## $ age_group                                       <fct> Early neonatal, Ear...
## $ ca_supp                                         <fct> NO, YES, YES, YES, ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{final_dataset }\OperatorTok{%>%}\StringTok{ }\NormalTok{head}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 18
##   item  item_outcome gender lbw_sg_cat exposed_in item_age_group
##   <chr> <chr>        <fct>  <chr>      <chr>      <chr>         
## 1 death neonatal_pr~ Male   <NA>       <NA>       early_neonatal
## 2 death neonatal_pr~ Male   <NA>       <NA>       early_neonatal
## 3 death neonatal_pr~ Male   <NA>       <NA>       early_neonatal
## 4 death neonatal_pr~ Male   <NA>       <NA>       early_neonatal
## 5 death neonatal_pr~ Male   <NA>       <NA>       early_neonatal
## 6 death neonatal_pr~ Male   <NA>       <NA>       early_neonatal
## # ... with 12 more variables: total_population_untracked <dbl>,
## #   total_population_tracked <dbl>, total_population <dbl>,
## #   total_population_living <dbl>, total_population_dead <dbl>,
## #   input_draw <dbl>, random_seed <dbl>, simulation_run_time <dbl>,
## #   calcium_supplementation_intervention.proportion <chr>, value <dbl>,
## #   age_group <fct>, ca_supp <fct>
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{final_dataset }\OperatorTok{%>%}\StringTok{ }\KeywordTok{count}\NormalTok{(item)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 26 x 2
##    item                                                                        n
##    <chr>                                                                   <int>
##  1 death                                                                  2.56e5
##  2 diarrheal_diseases_event_count                                         4.00e3
##  3 diarrheal_diseases_prevalent_cases_at_sim_end                          4.00e3
##  4 hemolytic_disease_and_other_neonatal_jaundice_event_count              4.00e3
##  5 hemolytic_disease_and_other_neonatal_jaundice_prevalent_cases_at_sim_~ 4.00e3
##  6 low_birth_weight_and_short_gestation                                   4.64e6
##  7 lower_respiratory_infections_event_count                               4.00e3
##  8 lower_respiratory_infections_prevalent_cases_at_sim_end                4.00e3
##  9 measles_event_count                                                    4.00e3
## 10 measles_prevalent_cases_at_sim_end                                     4.00e3
## # ... with 16 more rows
\end{verbatim}

\hypertarget{crude-death-rate}{%
\subsubsection{crude death rate:}\label{crude-death-rate}}

I thouhgt this is the way to calculate CDR by first, selecting only
person\_time rows\ldots{}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{crude_rate <-}\StringTok{ }\NormalTok{final_dataset }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(item }\OperatorTok{==}\StringTok{ 'person_time'}\NormalTok{) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{crude_death_rate_per_100000 =}\NormalTok{ (total_population_dead }\OperatorTok{/}\StringTok{ }\NormalTok{total_population_tracked)}\OperatorTok{*}\StringTok{ }\DecValTok{100000}\NormalTok{) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{select}\NormalTok{(item, gender, item_age_group,}
\NormalTok{         total_population_dead, total_population_tracked, }
\NormalTok{         crude_death_rate_per_}\DecValTok{100000}\NormalTok{, ca_supp)}
\end{Highlighting}
\end{Shaded}

..and then try to plot CDR density plot by calcium supp, gender and age
groups.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{crude_rate }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(crude_death_rate_per_}\DecValTok{100000}\NormalTok{, }
             \DataTypeTok{color =}\NormalTok{ ca_supp))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_density}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{facet_grid}\NormalTok{(gender }\OperatorTok{~}\StringTok{ }\NormalTok{item_age_group)}\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_light}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_x_continuous}\NormalTok{(}\DataTypeTok{breaks =} \KeywordTok{c}\NormalTok{(}\DecValTok{10000}\NormalTok{, }\DecValTok{12000}\NormalTok{, }\DecValTok{14000}\NormalTok{))}\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{labels =} \KeywordTok{label_number}\NormalTok{())}\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title =} \StringTok{'Crude Death Rate per 100 000'}\NormalTok{,}
       \DataTypeTok{subtitle =} \StringTok{'By gender and age group'}\NormalTok{,}
       \DataTypeTok{color =} \StringTok{'Calcium'}\NormalTok{,}
       \DataTypeTok{x=}\StringTok{''}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{plot.title =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{size =} \DecValTok{20}\NormalTok{),}
        \DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle =} \DecValTok{45}\NormalTok{, }
                                   \DataTypeTok{hjust =} \DecValTok{1}\NormalTok{),}
        \DataTypeTok{legend.position =} \StringTok{'bottom'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{ca_script_1_files/figure-latex/unnamed-chunk-19-1.pdf}

\end{document}
